version: '3.3'
services:
  db:
    image: mysql
    container_name: 'MySQL_DB'
    environment:
      MYSQL_DATABASE: 'api_pedido'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'pedido'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - api_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'Rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  my-db:

