version: '3.3'
services:
  mysqldb:
    image: mysql
    container_name: 'MysqlDb'
    environment:
      MYSQL_DATABASE: 'api_pedido'
      MYSQL_USER: 'api'
      MYSQL_PASSWORD: 'pedido'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - api_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'Rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - api_network

  api-pedido:
    container_name: 'ApiPedido'
    depends_on:
      - mysqldb
      - rabbitmq
    build: .
    restart: on-failure
    environment:
      MYSQL_HOST: 'mysqldb'
      RABBIT_HOST: 'rabbitmq'
      RABBIT_USER: 'guest'
      RABBIT_PASS: 'guest'
    ports:
      - 8080:8080
    expose:
      - '8080'
    volumes:
      - api-pedido-vol:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - api_network

networks:
  api_network:
    driver: bridge

volumes:
  mysql-db:
  api-pedido-vol:

